export default function () {
  return {
    status: '',
    token: localStorage.getItem('tokenchi') || '',
    user : {},
    pedido:[],
    usuarios:false,
    clientes:false,
    productos:false,
    inventario:false,
    ventadetalle:false,
    historialventadetalle:false,
    ventalocal:false,
    historialventalocal:false,
    empleados:false,
    reportes:false,
    gastos:false,
    historialprestamo:false,
    anularventa:false,
    ruta:false,
    anularprestamo:false,
    reimpresion:false,
    eliminargasto:false,
    cobrardetalle:false,
    cobrarlocal:false,
    cobrarruta:false,
    cajachica:false,
    editalmacen:false,
  }
}
